services:

  mongo:
    image: mongo:8.0.13
    restart: always
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORTS:-27017}:27017
    labels:
      kompose.service.healthcheck.liveness.tcp_port: ${MONGO_PORTS:-27017}
      kompose.volume.storage-class-name: longhorn
      kompose.volume.type: persistentVolumeClaim
      kompose.service.type: clusterip
      kompose.volume.size: 5Gi

  bf-demo:
    image: andrewthomaslee/bf-demo:n3pkzip20xr3s5vkzhqlnmhci29yflhi
    restart: always
    depends_on:
      - mongo
    environment:
      - DB_URI=${DB_URI:-mongodb://mongo}
      - SECRET_KEY=${SECRET_KEY:-should-be-changed}
      - FAKE_DATA=${FAKE_DATA:-True}
    networks:
      - backend
    tty: true
    stdin_open: true
    ports:
      - ${PORTS:-7999}:7999
    labels:
      kompose.security-context.fsgroup: 1000
      kompose.service.healthcheck.liveness.tcp_port: ${PORTS:-7999}
      kompose.service.healthcheck.readiness.http_get_port: ${PORTS:-7999}
      kompose.service.healthcheck.readiness.http_get_path: /health
      kompose.service.type: clusterip

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge