apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.kompose.yml
    kompose.security-context.fsgroup: "1000"
    kompose.service.healthcheck.liveness.tcp_port: "7999"
    kompose.service.healthcheck.readiness.http_get_path: /health
    kompose.service.healthcheck.readiness.http_get_port: "7999"
    kompose.service.type: clusterip
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: bf-demo
  name: bf-demo
spec:
  ports:
    - name: "7999"
      port: 7999
      targetPort: 7999
  selector:
    io.kompose.service: bf-demo
  type: ClusterIP
