apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.app: mongo-data
  name: mongo-data
  namespace: bf-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
