apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.kompose.yml
    kompose.service.healthcheck.liveness.tcp_port: "27017"
    kompose.service.type: clusterip
    kompose.version: 1.37.0 (HEAD)
    kompose.volume.size: 5Gi
    kompose.volume.storage-class-name: longhorn
    kompose.volume.type: persistentVolumeClaim
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
  type: ClusterIP
