apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest/ -n bff-demo --pvc-request-size 2G
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: bff-demo
  name: bff-demo
  namespace: bff-demo
spec:
  ports:
    - name: "7999"
      port: 7999
      targetPort: 7999
  selector:
    io.kompose.service: bff-demo
