apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-data
  name: mongo-data
  namespace: bff-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
