apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest/ -n bff-demo --pvc-request-size 2G
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: bff-demo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
